name: instantpure
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.4
  - matplotlib=3.6.3
  - pandas=1.5.3
  - opencv
  - pytorch::pytorch=2.4.0
  - pytorch::torchvision=0.19.0
  - pip:
      - accelerate==0.29.3
      - advertorch==0.2.3
      - advex_uar==0.0.6.dev0
      - git+https://github.com/fra31/auto-attack.git
      - bitsandbytes==0.42.0
      - colorama==0.4.6
      - datasets==2.19.1
      - deeplake
      - diffusers==0.30.3
      - lpips==0.1.4
      - packaging==25.0
      - peft==0.10.0
      - Pillow==11.2.1
      - safetensors==0.5.3
      - torcheval==0.0.7
      - torchmetrics==0.6.0
      - tqdm>=4.62.1
      - transformers==4.40.1
      - xformers==0.0.27.post2
